# Generated by Django 5.1.1 on 2024-10-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('EZ', 'EASY'), ('MD', 'MIDDLE'), ('HR', 'HARD'), ('IN', 'INSANE')], default='EASY', max_length=2),
        ),
    ]
