# Generated by Django 5.1.1 on 2024-11-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pc',
            field=models.CharField(choices=[('Course', 'Course'), ('Project', 'Project')], default='Course', max_length=7),
        ),
    ]
