# Generated by Django 5.1.1 on 2024-10-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_test_testing_question_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
