# Generated by Django 5.1.1 on 2024-10-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.FileField(default='1.png', upload_to='images'),
        ),
    ]
