# Generated by Django 5.1.1 on 2024-10-09 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_delete_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='question_text',
        ),
        migrations.AddField(
            model_name='testing',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testing',
            name='text',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testing',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
    ]
