# Generated by Django 5.1.1 on 2024-11-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
