# Generated by Django 5.1.1 on 2024-11-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_module_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='is_done',
        ),
        migrations.AddField(
            model_name='course',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
