# Generated by Django 5.1.1 on 2024-10-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_testing_question_text_testing_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='course',
        ),
    ]
