# Generated by Django 5.1.1 on 2024-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.FileField(upload_to='images'),
        ),
    ]
