# Generated by Django 5.1.1 on 2024-10-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_testing_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='text',
        ),
        migrations.AddField(
            model_name='testing',
            name='question_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testing',
            name='correct_answer',
            field=models.CharField(max_length=250),
        ),
    ]
