# Generated by Django 5.1.1 on 2024-10-11 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_test_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.module'),
            preserve_default=False,
        ),
    ]
