# Generated by Django 5.1.1 on 2024-10-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_test_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='module',
        ),
    ]
