# Generated by Django 5.1.1 on 2024-10-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0018_test_module'),
        ('students', '0005_remove_userprofile_user_delete_useranswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='module',
        ),
        migrations.RemoveField(
            model_name='test',
            name='owner',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model_in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
